### ISSUE TITLE
Wordnik Api

### ISSUE THREAD

**Issue by sondirewolf** [wordnik/wordnik-php#7]
Hi! I've been trying to get an API key for the last few days. I keep seeing that it is supposed to be at the bottom of the settings page but it shows . Here is a picture of what my account looks like. Your API key is: Your API key is not yet available. Check back in a few days. Please help!

**Comment by emckean** [comment]
Hi this is not an issue with this repo; I'm closing it. For API key questions please email apiteam@wordnik.com
